### ISSUE TITLE
Task 1: UX Task

### ISSUE THREAD

**Issue by nityagupta6** [opencodeiiita/CampusOLX#2]
**OPEN TO ALL.**
NO need to claim this issue.
NO submission will be accepted after **20th December, 11:59 PM**.

Your **First Task** is based on a basic understanding of User Experience and User flow. This is a **10 points** task.

CampusOLX, as the name implies, is a local online marketplace specifically designed for students at IIIT-A to buy and sell second-hand items, such as furniture, electronics, and other household goods. By providing a platform for students to sell items they no longer need or use, CampusOLX can help students save money on living expenses and make it easier for them to find affordable products. It can also be a convenient way for students to sell items they no longer need, allowing them to declutter and make some extra money. The website provides the convenience of being able to buy and sell items directly with other students on campus may make it an appealing option for students at IIIT-A.

The task needs to be done on **FigJam**. FigJam is free to use and doesn't need to download. It is very easy to learn and hardly takes 15 minutes to learn. If you are unclear on how to use it, check the tutorial here: [https://www.youtube.com/watch?v=RVNuArHH5WM](https://www.youtube.com/watch?v=RVNuArHH5WM)

## Procedure:

1. Think about how the flow of the website will be for an average user who has just clicked on the website’s link and is opening it for the first time. The user is assumed to be unclear about the functionalities of the website.
2. You have to decide how the user will move through the website, what steps will he need to take, and in which order, for eg. the user first might need to sign up to the website, might want to buy or sell an item, maybe wants to search whether an item is on sale, etc.
3. Essentially, you have to design a ‘single flow’ for a user who wants to buy an item and a user who wants to sell an item. From the user's first visit to the website to the completion of the task, he or she intended to complete.
4. Finally, create your ideal user flow in a FigJam file and provide its link (in a .txt file). Submit your txt files in **'Task 1: UX Task'** folder only.

</br>

If you are unclear about user flow diagrams check this short video here: [https://www.youtube.com/watch?v=cvYhuowazh0](https://www.youtube.com/watch?v=cvYhuowazh0)

</br>

> ✨PRO-TIP: The secret to creating a powerful user flow is to first research and gain an understanding of how a given problem statement is addressed. As a result, the first and most important thing you must do before beginning to build your user flow is to search other websites that deal with a similar problem statement of buying and selling goods. And take note of the key features they use (basically their user flow).
> 

</br>

## **MDC (Minimum Design Criteria):**

The user flow can be very simple, but it must at least fulfill the basic functionality of the website, which is that users should be able to buy and sell items. Make sure that the user-flow looks like a user flow. The flow should start with the user entering the site for the first time and continue until the user buys or sells a product. Try to explain in detail each and every feature you add, and keep in mind that don't add unnecessary features. The more elaborate the user flow higher the chances of PR being accepted. 

> ✨PRO-TIP: Try to make an elaborate user-flow…that makes your task of building the further website way too easy. meticulously decide upon each feature you add.
> 

For any doubts related to the task or the submission process, you can always ping us on [discord](https://discord.com/channels/885149696249708635/1052176133954744391). Use the tags to notify the mentors. We will be happy to help.

**Comment by Siddhant-Agarwal4583** [comment]
claim
