### ISSUE TITLE
Frontend-Forum Collab Task

### ISSUE THREAD

**Issue by nityagupta6** [opencodeiiita/CampusOLX#50]
The forum is a project where students of IIITA can ask their doubts or share their experiences with each other. They can join spaces or communities too.
Your Task is to design a Profile page for this website on Figma.

---
The dashboard should include all necessary information of a user like a name, profile image, the question asked/solved, communities,  reward, etc...
You can take references from any other Forum website. The deadline is tomorrow 27th Dec 11:59 P.M

## Guidelines
- The UI should be clean.
- Do the task in a Figma file and provide its link (in a .txt file). Submit your txt files in the Frontend-Forum Collab Task folder only.
## Minimum Design Criteria
The profile page should look like a webpage. The design should not look like a PDF but rather a webpage. Make sure that the theme matches with that the theme of the entire website, all major features of the profile related to a forum page must be present. Create a beautiful UI so that the user wishes to use the website. The placement of different features must be appropriate on the web page.
## Note
- The top 3 designs will be selected and will be rewarded with points.
- The final decision will be taken by mentors.
- As it is open to all issues, therefore, is no need to claim.
- Make sure you follow the given template before making the pull request.

**Comment by Kali-Decoder** [comment]
Claim
